version: '3.9'

name: miniverse

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: miniverse
    volumes:
      - ./src/main/resources/database/digilib.sql:/docker-entrypoint-initdb.d/digilib.sql
    ports:
      - "3307:3306"

  app:
    container_name: miniverse-api
    environment:
      SPRING_PROFILES_ACTIVE: docker
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 2
        window: 60s
    ports:
      - "8080:8080"
    depends_on:
      - mysql
